version: "3.8"
services:
  server:
    image: 'nginx:stable-alpine'
    container_name: server
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    platform: linux/x86_64
    image: 'mysql:5.7'
    container_name: mysql
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql:delegated"
  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www/html
  # artisan:
  # npm: